# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule = blur on, ignore_alpha 1, match:namespace rofi
layerrule = blur on,                 match:namespace logout_dialog

layerrule = no_anim on,              match:namespace ^(dms)$

layerrule = blur on,                 match:namespace dms:bar
layerrule = blur on, ignore_alpha 0, match:namespace dms:dock
layerrule = blur on, ignore_alpha 0, match:namespace dms:clipboard
layerrule = blur on, ignore_alpha 0, match:namespace dms:dock-context-menu
layerrule = blur on, ignore_alpha 0, match:namespace dms:notification-center-modal
layerrule = blur on, ignore_alpha 0, match:namespace dms:polkit
layerrule = blur on, ignore_alpha 0, match:namespace dms:spotlight

layerrule = blur on, ignore_alpha 0, match:namespace dms:app-launcher
layerrule = blur on, ignore_alpha 0, match:namespace dms:battery
layerrule = blur on, ignore_alpha 0, match:namespace dms:clipboard-popout
layerrule = blur on, ignore_alpha 0, match:namespace dms:control-center
layerrule = blur on, ignore_alpha 0, match:namespace dms:dash
layerrule = blur on, ignore_alpha 0, match:namespace dms:notification-center-popout
layerrule = blur on, ignore_alpha 0, match:namespace dms:notification-popup
layerrule = blur on, ignore_alpha 0, match:namespace dms:popout
layerrule = blur on, ignore_alpha 0, match:namespace dms:process-list-popout
layerrule = blur on, ignore_alpha 0, match:namespace dms:osd
layerrule = blur on, ignore_alpha 1, match:namespace dms:toast
layerrule = blur on, ignore_alpha 0, match:namespace dms:vpn
layerrule = blur on, ignore_alpha 0, match:namespace dms:tray-menu-window
layerrule = blur on, ignore_alpha 0, match:namespace dms:plugins:.*

layerrule = blur on, ignore_alpha 0, match:namespace dms:desktop-widget:desktopClock:.*
