return {
    'MeanderingProgrammer/treesitter-modules.nvim',
    dependencies = { 'nvim-treesitter/nvim-treesitter' },
    opts = {
        -- enable syntax highlighting
        highlight = { enable = true, additional_vim_regex_highlighting = false },
        -- enable indentation
        indent = { enable = true },
        -- enable folding
        fold = { enable = true },
        -- ensure these language parsers are installed
        ensure_installed = {
            'arduino',
            'astro',
            'bash',
            'c',
            'cmake',
            'commonlisp',
            'cpp',
            'css',
            'csv',
            'desktop',
            'dockerfile',
            'git_config',
            'gitignore',
            'glsl',
            'go',
            'gomod',
            'gosum',
            'html',
            'ini',
            'javascript',
            'json',
            'linkerscript',
            'lua',
            'make',
            'markdown',
            'markdown_inline',
            'php',
            'phpdoc',
            'python',
            'query',
            'regex',
            'rust',
            'scss',
            'sql',
            'ssh_config',
            'svelte',
            'tsx',
            'toml',
            'typescript',
            'typst',
            'vim',
            'vimdoc',
            'xml',
            'yaml',
            'zig',
            'zsh',
        },
        incremental_selection = {
            enable = true,
            keymaps = {
                init_selection = '<C-Space>',
                node_incremental = '<C-Space>',
                scope_incremental = false,
                node_decremental = '<bs>',
            },
        },
    },
}
