#include "build.h"

#define _PROJECT_NAME       "@PROJECT_NAME@"
#define _PROJECT_VERSION    "@PROJECT_VERSION@@PROJECT_DEBUG@"
#define _BUILD_TIMESTAMP    "@BUILD_TIMESTAMP@"

#define _PROJECT_BUILD_ID   "@PROJECT_BUILD_ID@"

const char *PROJECT_NAME = _PROJECT_NAME;
const char *PROJECT_VERSION = _PROJECT_VERSION;
const char *BUILD_TIMESTAMP = _BUILD_TIMESTAMP;
const char *PROJECT_BUILD_ID = _PROJECT_BUILD_ID;
